import { AppSettings, FilingCode, SymbolDefinition, Abbreviation } from '../types';

export const DEFAULT_FILING_CODES: FilingCode[] = [
  {
    id: 'code-a145',
    code: 'A145',
    name: 'ANTH 145',
    tags: ['anthropology', 'anth145'],
    folder: 'Courses/ANTH 145',
    description: 'Introduction to Cultural Anthropology',
  },
  {
    id: 'code-a329',
    code: 'A329',
    name: 'ANTH 329',
    tags: ['anthropology', 'anth329'],
    folder: 'Courses/ANTH 329',
    description: 'Immigration and Cultural Change',
  },
  {
    id: 'code-e428',
    code: 'E428',
    name: 'ENG 428',
    tags: ['english', 'eng428'],
    folder: 'Courses/ENG 428',
    description: 'Literary Theory and Cultural Critique',
  },
  {
    id: 'code-p280',
    code: 'P280',
    name: 'PPPM 280',
    tags: ['pppm', 'pppm280'],
    folder: 'Courses/PPPM 280',
    description: 'Introduction to Public Policy',
  },
  {
    id: 'code-p422',
    code: 'P422',
    name: 'PPPM 422',
    tags: ['pppm', 'pppm422'],
    folder: 'Courses/PPPM 422',
    description: 'Public Policy Analysis',
  },
  {
    id: 'code-todo',
    code: 'TODO',
    name: 'Task Inbox',
    tags: ['tasks', 'todo'],
    folder: 'Tasks',
    description: 'General actionable task list',
  },
];

export const INBOX_FILING_CODE: FilingCode = {
  id: 'code-inbox',
  code: 'INBOX',
  name: 'Inbox',
  tags: ['inbox'],
  folder: 'Inbox',
  description: 'Uncategorized notes',
};

export const DEFAULT_SYMBOLS: SymbolDefinition[] = [
  {
    id: 'sym-bullet',
    char: '●',
    name: 'Bullet',
    type: 'bullet',
    markdownPattern: '- {text}',
    description: 'Filled circle at start of line for regular bullet points.',
    isDefault: true,
  },
  {
    id: 'sym-task',
    char: '□',
    name: 'Task',
    type: 'task',
    markdownPattern: '- [ ] {text}{date_suffix}',
    description: 'Empty square for pending task. Includes converted written date (e.g. 📅 YYYY-MM-DD).',
    isDefault: true,
  },
  {
    id: 'sym-done-task',
    char: '☑',
    name: 'Done Task',
    type: 'done_task',
    markdownPattern: '- [x] {text}',
    description: 'Checked square for completed task.',
    isDefault: true,
  },
  {
    id: 'sym-flashcard',
    char: '▲',
    name: 'Flashcard / Vocab',
    type: 'flashcard',
    markdownPattern: '{front}::{back}',
    description: 'Triangle symbol. Written "front :: back" or "front = back". Appended to ## Flashcards section.',
    isDefault: true,
  },
  {
    id: 'sym-question',
    char: '?',
    name: 'Question',
    type: 'question',
    markdownPattern: '- [ ] ❓ {text} #question',
    description: 'Question mark inside a circle. Question to look up or ask in lecture/office hours.',
    isDefault: true,
  },
  {
    id: 'sym-important',
    char: '★',
    name: 'Important / Exam',
    type: 'important',
    markdownPattern: '> [!important]\n> {text}',
    description: 'Star symbol. Crucial concept, likely to appear on test.',
    isDefault: true,
  },
  {
    id: 'sym-quote',
    char: '"',
    name: 'Direct Quote',
    type: 'quote',
    markdownPattern: '> "{text}" (p. {page}) #quote',
    description: 'Quote marks. Direct quote with page number written after, e.g. (p. 42) or (p. ?).',
    isDefault: true,
  },
  {
    id: 'sym-link',
    char: '→',
    name: 'Topic Link',
    type: 'link',
    markdownPattern: '→ [[{text}]]',
    description: 'Arrow symbol. Obsidian wikilink to another note or concept, collected in ## Related.',
    isDefault: true,
  },
  {
    id: 'sym-idea',
    char: '~',
    name: 'Personal Idea',
    type: 'idea',
    markdownPattern: '> [!idea]\n> {text} #idea',
    description: 'Wavy line. Personal insight or synthesis, not from reading/lecture.',
    isDefault: true,
  },
  {
    id: 'sym-event',
    char: '◇',
    name: 'Event / Date',
    type: 'event',
    markdownPattern: '- 📅 {date} {text} #event',
    description: 'Diamond symbol. Event or date to remember, featured in the top summary block.',
    isDefault: true,
  },
];

export const DEFAULT_ABBREVIATIONS: Abbreviation[] = [
  { id: 'abbr-1', abbr: 'w/', expansion: 'with' },
  { id: 'abbr-2', abbr: 'w/o', expansion: 'without' },
  { id: 'abbr-3', abbr: 'b/c', expansion: 'because' },
  { id: 'abbr-4', abbr: 'imp', expansion: 'important' },
  { id: 'abbr-5', abbr: 'dept', expansion: 'department' },
  { id: 'abbr-6', abbr: 'defn', expansion: 'definition' },
  { id: 'abbr-7', abbr: 'ex', expansion: 'example' },
  { id: 'abbr-8', abbr: 'info', expansion: 'information' },
  { id: 'abbr-9', abbr: 'ch', expansion: 'chapter' },
  { id: 'abbr-10', abbr: 'sec', expansion: 'section' },
];

export const INITIAL_SETTINGS: AppSettings = {
  filingCodes: DEFAULT_FILING_CODES,
  symbols: DEFAULT_SYMBOLS,
  handwritingReferences: [],
  abbreviations: DEFAULT_ABBREVIATIONS,
  theme: 'system',
  lowConfidenceThreshold: 0.8,
  autoCleanPaper: true,
  contrastBoost: 1.5,
};
